options  ( skip=1 ) 
LOAD DATA
INFILE ADDRESS.data
TRUNCATE
INTO TABLE ADDRESS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ADDRESSID DECIMAL EXTERNAL 
,ADDRESSLINE1 CHAR(100)
,ADDRESSLINE2 CHAR(100)
,ADDRESSLINE3 CHAR(100)
,ADDRESSLINE4 CHAR(100)
,CITY CHAR(100)
,COUNTRYSUBDIVISIONCODEID DECIMAL EXTERNAL 
,POSTALCODE CHAR(15)
,COUNTRY DECIMAL EXTERNAL 
,COUNTRYSUBDIVISION CHAR(3)
,DOCUMENTKEY CHAR(36)
,LASTUPDATEDBY CHAR(36)
)