options  ( skip=1 ) 
LOAD DATA
INFILE ASPNET_USERSINROLES.data
TRUNCATE
INTO TABLE ASPNET_USERSINROLES
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( USERID CHAR(36)
,ROLEID CHAR(36)
)