options  ( skip=1 ) 
LOAD DATA
INFILE ASPNET_SCHEMAVERSIONS.data
TRUNCATE
INTO TABLE ASPNET_SCHEMAVERSIONS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( FEATURE CHAR(128)
,COMPATIBLESCHEMAVERSION CHAR(128)
,ISCURRENTVERSION DECIMAL EXTERNAL "decode(:ISCURRENTVERSION ,'true',1,'false',0, 0)"
)