options  ( skip=1 ) 
LOAD DATA
INFILE ASPNET_ROLES.data
TRUNCATE
INTO TABLE ASPNET_ROLES
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( APPLICATIONID CHAR(36)
,ROLEID CHAR(36)
,ROLENAME CHAR(256)
,LOWEREDROLENAME CHAR(256)
,DESCRIPTION CHAR(256)
)