options  ( skip=1 ) 
LOAD DATA
INFILE ASPNET_APPLICATIONS.data
TRUNCATE
INTO TABLE ASPNET_APPLICATIONS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( APPLICATIONNAME CHAR(256)
,LOWEREDAPPLICATIONNAME CHAR(256)
,APPLICATIONID CHAR(36)
,DESCRIPTION CHAR(256)
)