options  ( skip=1 ) 
LOAD DATA
INFILE AUDITHISTORYROLES.data
TRUNCATE
INTO TABLE AUDITHISTORYROLES
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( AUDITHISTORYROLENAME CHAR(255)
)