options  ( skip=1 ) 
LOAD DATA
INFILE COMMENTENTITY_HISTORY.data
TRUNCATE
INTO TABLE COMMENTENTITY_HISTORY
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,COMMENTID DECIMAL EXTERNAL 
,COMMENT_TEXT CHAR(4000)
,ENTITYID DECIMAL EXTERNAL 
,ENTITYTYPEID DECIMAL EXTERNAL 
,LASTUPDATEDBY CHAR(36)
,LASTUPDATEDUTC DATE "YYYY-MM-DD HH24:MI:SS" 
)