options  ( skip=1 ) 
LOAD DATA
INFILE COMPANYROLLUP.data
TRUNCATE
INTO TABLE COMPANYROLLUP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( COMPANYROLLUPID DECIMAL EXTERNAL 
,SUPPLIERCOMPANYPROFILEID DECIMAL EXTERNAL 
,OVERALLSTATUSID DECIMAL EXTERNAL 
,LASTUPDATEDUTC DATE "YYYY-MM-DD HH24:MI:SS" 
)