options  ( skip=1 ) 
LOAD DATA
INFILE CONTACTTYPE.data
TRUNCATE
INTO TABLE CONTACTTYPE
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( CONTACTTYPEID DECIMAL EXTERNAL 
,CONTACTTYPETEXTID CHAR(36)
,DEFINITIONTEXTID CHAR(36)
,ACTIVE  "decode(:ACTIVE ,'true','T','false','F', 'F')"
)