options  ( skip=1 ) 
LOAD DATA
INFILE DOC_DOCUMENT.data
TRUNCATE
INTO TABLE DOC_DOCUMENT
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( DOC_DOCUMENTID DECIMAL EXTERNAL 
,DOCUMENTID CHAR(50)
,DATARECIPIENTGLN CHAR(50)
,DOCUMENTCURRENTSTATUS DECIMAL EXTERNAL 
,FILECREATEDDATE DATE "YYYY-MM-DD HH24:MI:SS" 
,CONFIRMATIONRECIEVEDDATE DATE "YYYY-MM-DD HH24:MI:SS" 
,DOC_MESSAGEID DECIMAL EXTERNAL 
,COMPANYID DECIMAL EXTERNAL 
,DOCUMENTEXCEPTION CHAR(1000000)
)