options  ( skip=1 ) 
LOAD DATA
INFILE DOC_MESSAGE.data
TRUNCATE
INTO TABLE DOC_MESSAGE
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( DOC_MESSAGEID DECIMAL EXTERNAL 
,MESSAGEID CHAR(100)
,CREATIONDATETIME DATE "YYYY-MM-DD HH24:MI:SS" 
,SENDER CHAR(50)
,RECEIVER CHAR(50)
,DOCUMENTCOUNT DECIMAL EXTERNAL 
)