options  ( skip=1 ) 
LOAD DATA
INFILE ENTITYCOMMENT.data
TRUNCATE
INTO TABLE ENTITYCOMMENT
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ENTITYCOMMENT_ID  DECIMAL EXTERNAL 
,ENTITYTYPEID DECIMAL EXTERNAL 
,ENTITYID DECIMAL EXTERNAL 
,CREATEDATE  DATE "YYYY-MM-DD HH24:MI:SS" 
,USERID CHAR(36)
,ACTINGROLE CHAR(50)
,COMMENT_TEXT CHAR(100000)
)


  