options  ( skip=1 ) 
LOAD DATA
INFILE ENTITYTYPE.data
TRUNCATE
INTO TABLE ENTITYTYPE
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ENTITYTYPEID DECIMAL EXTERNAL 
,ENTITYNAME CHAR(50)
)