options  ( skip=1 ) 
LOAD DATA
INFILE ETHNICITYTYPE.data
TRUNCATE
INTO TABLE ETHNICITYTYPE
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ETHNICITYTYPEID DECIMAL EXTERNAL 
,COMPANYOWNERSHIPETHNICITYTEXTI CHAR(36)
,DESCRIPTIONTEXTID CHAR(36)
)