options  ( skip=1 ) 
LOAD DATA
INFILE EXPORT_PROGRESS.data
TRUNCATE
INTO TABLE EXPORT_PROGRESS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,REQUESTID CHAR(36)
,REQUESTSTART DATE "YYYY-MM-DD HH24:MI:SS" 
,REQUESTEND DATE "YYYY-MM-DD HH24:MI:SS" 
,REQUESTER CHAR(50)
,PROGRESS DECIMAL EXTERNAL 
,STATUS CHAR(255)
)