options  ( skip=1 ) 
LOAD DATA
INFILE FIELDDEFINITIONROLEPERMISSION.data
TRUNCATE
INTO TABLE FIELDDEFINITIONROLEPERMISSION
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,FIELDDEFINITIONID DECIMAL EXTERNAL 
,ROLE CHAR(36)
,READONLY DECIMAL EXTERNAL "decode(:READONLY,'true',1,'false',0, 0)"
,VISIBLE DECIMAL EXTERNAL "decode(:VISIBLE,'true',1,'false',0, 1)"
)