options  ( skip=1 ) 
LOAD DATA
INFILE FIELDDEFINITIONROLEENTITYPERMI.data
TRUNCATE
INTO TABLE FIELDDEFINITIONROLEENTITYPERMI
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,FIELDDEFINITIONID DECIMAL EXTERNAL 
,ROLEID CHAR(36)
,ENTITYTYPEID DECIMAL EXTERNAL 
,ENTITYID DECIMAL EXTERNAL 
,READONLY DECIMAL EXTERNAL "decode(:READONLY ,'true',1,'false',0, 0)"
,ACTIVATIONSTATUS DECIMAL EXTERNAL 
)