options  ( skip=1 ) 
LOAD DATA
INFILE FIELDDEFINITIONROLEVALIDATION.data
TRUNCATE
INTO TABLE FIELDDEFINITIONROLEVALIDATION
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,FIELDDEFINITIONID DECIMAL EXTERNAL 
,ROLE CHAR(36)
,REQUIRED DECIMAL EXTERNAL "decode(:REQUIRED,'true',1,'false',0, 0)"
)