options  ( skip=1 ) 
LOAD DATA
INFILE FIELDGROUP.data
TRUNCATE
INTO TABLE FIELDGROUP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( FIELDGROUPID DECIMAL EXTERNAL 
,GROUPNAME_OLD CHAR(100)
,GROUPNAMETEXTID CHAR(36)
,ENTITYTYPEID DECIMAL EXTERNAL 
,GROUPSEQUENCE DECIMAL EXTERNAL 
)