options  ( skip=1 ) 
LOAD DATA
INFILE GLNGENERATORSEEDS.data
TRUNCATE
INTO TABLE GLNGENERATORSEEDS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( GLNPREFIX CHAR(12)
,COMMENT_ CHAR(100)
,LASTASSIGNEDSEED CHAR(12)
,INCREMENT_ DECIMAL EXTERNAL 
,LASTASSIGNEDDATE CHAR(200)
,FLOOR CHAR(12)
,CEILING CHAR(12)
)