options  ( skip=1 ) 
LOAD DATA
INFILE GROUPROLEACCESS.data
TRUNCATE
INTO TABLE GROUPROLEACCESS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,FIELDGROUPID DECIMAL EXTERNAL 
,ROLEID CHAR(36)
,ACTION CHAR(10)
)