options  ( skip=1 ) 
LOAD DATA
INFILE IMPORTFACILITYXREF.data
TRUNCATE
INTO TABLE IMPORTFACILITYXREF
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( STETONFACILITYID CHAR(255)
,MERLINFACILITYID DECIMAL EXTERNAL 
)