options  ( skip=1 ) 
LOAD DATA
INFILE IMPORTTRADINGAREAS.data
TRUNCATE
INTO TABLE IMPORTTRADINGAREAS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( COMPANYID CHAR(255)
,FACILITYID CHAR(255)
,AOW CHAR(255)
,REGION CHAR(255)
,COUNTRY CHAR(255)
,STATUS CHAR(255)
)