options  ( skip=1 ) 
LOAD DATA
INFILE IMPORTSUPPLIERXREF.data
TRUNCATE
INTO TABLE IMPORTSUPPLIERXREF
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( STETONCOMPANYID CHAR(255)
,MERLINCOMPANYID CHAR(255)
)