options  ( skip=1 ) 
LOAD DATA
INFILE IMPORTSTATUS.data
TRUNCATE
INTO TABLE IMPORTSTATUS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,ENTITYTYPEID DECIMAL EXTERNAL 
,ENTITYID DECIMAL EXTERNAL 
,REFERENCEIDTYPE CHAR(255)
,REFERENCEID CHAR(255)
,DOCUMENTSTATUS CHAR(25)
,ACTION CHAR(255)
,DATE_ DATE "YYYY-MM-DD HH24:MI:SS" 
)