options  ( skip=1 ) 
LOAD DATA
INFILE IMPORTNOTIFICATIONCONTACTS.data
TRUNCATE
INTO TABLE IMPORTNOTIFICATIONCONTACTS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ROLE CHAR(20)
,AOW CHAR(50)
,TYPE CHAR(20)
,CONTACT CHAR(255)
,FIRSTNAME CHAR(50)
,LASTNAME CHAR(50)
)