options  ( skip=1 ) 
LOAD DATA
INFILE LOCALTEXTCLEANER.data
TRUNCATE
INTO TABLE LOCALTEXTCLEANER
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,ISOCODE CHAR(10)
,SUBDIVISIONCODE CHAR(10)
,DIRTYNAME CHAR(2000)
,CLEANNAME CHAR(2000)
)