options  ( skip=1 ) 
LOAD DATA
INFILE MULTIVALUEFIELD.data
TRUNCATE
INTO TABLE MULTIVALUEFIELD
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( MULTIVALUEFIELDID DECIMAL EXTERNAL 
,ENTITYTYPEID DECIMAL EXTERNAL 
,ENTITYID DECIMAL EXTERNAL 
,FIELDDEFINITIONID DECIMAL EXTERNAL 
,SELECTEDVALUE DECIMAL EXTERNAL 
,DOCUMENTKEY CHAR(36)
,LASTUPDATEDBY CHAR(36)
)