options  ( skip=1 ) 
LOAD DATA
INFILE NAMEPREFIX.data
TRUNCATE
INTO TABLE NAMEPREFIX
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( NAMEPREFIXID DECIMAL EXTERNAL 
,NAMEPREFIXTEXTID CHAR(36)
,ACTIVE "decode(:ACTIVE ,'true','T','false','F', 'F')"
)