options  ( skip=1 ) 
LOAD DATA
INFILE NotificationContactResponsibility.data
TRUNCATE
INTO TABLE NCRESPONSIBIL_TEMP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,NOTIFICATIONCONTACTID DECIMAL EXTERNAL 
,ROLEID CHAR(36)
,TRADINGAREAID DECIMAL EXTERNAL 
,CATEGORYID DECIMAL EXTERNAL 
)