options  ( skip=1 ) 
LOAD DATA
INFILE NOTIFICATIONCONTACTOVERRIDE.data
TRUNCATE
INTO TABLE NCOVERRIDE_TEMP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
(  
 ENTITYTYPEID DECIMAL EXTERNAL 
,ENTITYID DECIMAL EXTERNAL 
,ROLEID CHAR(36)
,ContactID DECIMAL EXTERNAL 
)
