options  ( skip=1 ) 
LOAD DATA
INFILE NOTIFICATIONCONTACT.data
TRUNCATE
INTO TABLE NOTIFICATIONCONTACT_TEMP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,USERID CHAR(36)
)