options  ( skip=1, READSIZE=40627584) 
LOAD DATA
INFILE OIMXMLSNAPSHOT.data 
TRUNCATE
INTO TABLE OIMXMLSNAPSHOT
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
(ENTITYID DECIMAL EXTERNAL 
,ENTITYTYPEID DECIMAL EXTERNAL 
,DRAFTXML CHAR(12000000)
,FINALXML CHAR(12000000)
)