options  ( skip=1 ) 
LOAD DATA
INFILE PROCESSSTEPTYPE.data
TRUNCATE
INTO TABLE PROCESSSTEPTYPE
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( PROCESSSTEPTYPEID DECIMAL EXTERNAL 
,STEPTYPETEXTID CHAR(36)
,STEPTYPEDESCRIPTIONTEXTID CHAR(36)
,SYSTEMONLY DECIMAL EXTERNAL "decode(:SYSTEMONLY,'true',1,'false',0, 0)"
)