options  ( skip=1 ) 
LOAD DATA
INFILE PROPOSEDITEMGTIN.data
TRUNCATE
INTO TABLE PROPOSEDITEMGTIN
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,PROPOSEDITEMID DECIMAL EXTERNAL 
,UNITDESCRIPTOR CHAR(2)
,GTIN CHAR(14)
)