options  ( skip=1 ) 
LOAD DATA
INFILE PROPOSEDITEMDESCRIPTION.data
TRUNCATE
INTO TABLE PROPOSEDITEMDESCRIPTION
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,PROPOSEDITEMID DECIMAL EXTERNAL 
,LANGUAGECODE CHAR(2)
,DESCRIPTION CHAR(35)
)