options  ( skip=1 ) 
LOAD DATA
INFILE READYPROCESSSTEP.data
TRUNCATE
INTO TABLE READYPROCESSSTEP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( READYPROCESSSTEPID DECIMAL EXTERNAL 
,PROCESSSTEPTYPEID DECIMAL EXTERNAL 
)