options  ( skip=1 ) 
LOAD DATA
INFILE REMOVALREASON.data
TRUNCATE
INTO TABLE REMOVALREASON
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( REMOVALREASONID DECIMAL EXTERNAL 
,REMOVALREASONTEXTID CHAR(36)
)