options  ( skip=1 ) 
LOAD DATA
INFILE SUPPLIERCATEGORY.data
TRUNCATE
INTO TABLE SUPPLIERCATEGORY_TEMP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( SUPPLIERCATEGORYID DECIMAL EXTERNAL 
,CATEGORYTEXTID CHAR(36)
,CATEGORYDESCRIPTIONTEXTID CHAR(36)
,ACTIVE "decode(:ACTIVE ,'true','T','false','F', 'F')"
,PARENTSUPPLIERCATEGORYID  DECIMAL EXTERNAL
)
