options  ( skip=1 ) 
LOAD DATA
INFILE SUPPLIERSUBCATEGORY.data
TRUNCATE
INTO TABLE SUPPLIERSUBCATEGORY
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( SUBCATEGORYID DECIMAL EXTERNAL 
,SUBCATEGORYTEXTID CHAR(500)
,SUBCATEGORYTEXTDESCRIPTION CHAR(500)
,ACTIVE DECIMAL EXTERNAL 
,CATEGORYID DECIMAL EXTERNAL 
)