options  ( skip=1 ) 
LOAD DATA
INFILE SUPPLIERUSER.data
TRUNCATE
INTO TABLE SUPPLIERUSER
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( APPLICATIONID CHAR(36)
,USERID CHAR(36)
,SUPPLIERCOMPANYPROFILEID DECIMAL EXTERNAL 
)