options  ( skip=1 ) 
LOAD DATA
INFILE SWASTATUS.data
TRUNCATE
INTO TABLE SWASTATUS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( SWASTATUSID DECIMAL EXTERNAL 
,STATUSTEXTID CHAR(36)
,STATUSDEFINITIONTEXTID CHAR(36)
,ACTIVE "decode(:ACTIVE,'true','T','false','F', 'F')"
)