options  ( skip=1 ) 
LOAD DATA
INFILE TLOCALTEXT_TEMP.data
TRUNCATE
INTO TABLE TLOCALTEXT_TEMP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( LOCALTEXTID CHAR(36)
,CURRENTTEXT CHAR(2000)
,NEWTEXT CHAR(2000)
)