options  ( skip=1 ) 
LOAD DATA
INFILE TLOCALTEXT.data
TRUNCATE
INTO TABLE TLOCALTEXT
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( LOCALTEXTID CHAR(36)
,LOCALTEXTLANGUAGE CHAR(5)
,LOCALTEXT CHAR(2000)
)