options  ( skip=1 ) 
LOAD DATA
INFILE TRADINGAREA_BACKUP.data
TRUNCATE
INTO TABLE TRADINGAREA_BACKUP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( TRADINGAREAID DECIMAL EXTERNAL 
,AOWTEXTID CHAR(36)
,REGIONTEXTID CHAR(36)
,COUNTRYTEXTID CHAR(36)
,AOW DECIMAL EXTERNAL  "decode(:AOW,'true',1,'false',0, 0)"
,REGION DECIMAL EXTERNAL  "decode(:REGION ,'true',1,'false',0, 0)"
,COUNTRYCODE CHAR(36)
)