options  ( skip=1 ) 
LOAD DATA
INFILE TRADINGAREABACKUP.data
TRUNCATE
INTO TABLE TRADINGAREABACKUP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( TRADINGAREAID DECIMAL EXTERNAL 
,AOWTEXTID CHAR(36)
,REGIONTEXTID CHAR(36)
,COUNTRYTEXTID CHAR(36)
,AOW DECIMAL EXTERNAL 
,REGION DECIMAL EXTERNAL 
,COUNTRYCODE CHAR(36)
,ISDISABLED DECIMAL EXTERNAL 
)