options  ( skip=1 ) 
LOAD DATA
INFILE TRADINGAREASTATUS.data
TRUNCATE
INTO TABLE TRADINGAREASTATUS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( TRADINGAREASTATUSID DECIMAL EXTERNAL 
,STATUSVALUESTEXTID CHAR(36)
,COMPANYDEFINITIONTEXTID CHAR(36)
,FACILITYDEFINITIONTEXTID CHAR(36)
,ACTIVE "decode(:ACTIVE ,'true','T','false','F', 'F')"
)