options  ( skip=1 ) 
LOAD DATA
INFILE USERPASSWORDHISTORY.data
TRUNCATE
INTO TABLE USERPASSWORDHISTORY
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID DECIMAL EXTERNAL 
,USERID CHAR(36)
,PASSWORD CHAR(128)
,PASSWORDSALT CHAR(128)
,CHANGEDATE DATE "YYYY-MM-DD HH24:MI:SS" 
)