options  ( skip=1 ) 
LOAD DATA
INFILE USERDETAIL.data
TRUNCATE
INTO TABLE USERDETAIL
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( USERID CHAR(36)
,FIRSTNAME CHAR(100)
,LASTNAME CHAR(250)
)