options  ( skip=1 ) 
LOAD DATA
INFILE WFENTITYSETTING.data
TRUNCATE
INTO TABLE WF_ENTITY_TYPE_SETTINGS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ENTITY_TYPE DECIMAL EXTERNAL 
,DEFAULT_WORKFLOW_ID  CHAR(36) 
)