options  ( skip=1 ) 
LOAD DATA
INFILE WFFACILITYREADYSTEP.data
TRUNCATE
INTO TABLE WF_FACILITY_READY_STEP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ROLE_ID CHAR(200)
,STATUS DECIMAL EXTERNAL 
)