options  ( skip=1 ) 
LOAD DATA
INFILE WF_STEP_DEFINITION.data
TRUNCATE
INTO TABLE WF_STEP_DEFINITION
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( WF_STEP_DEF_ID CHAR(36) 
,WF_STEP_NAME CHAR(200)
,CURRENT_VERSION DECIMAL EXTERNAL 
,LOCKABLE  "decode(:LOCKABLE,'true',1,'false',0, 0)"
,WF_DEFINITION_ID CHAR(36) 
)