options  ( skip=1 ) 
LOAD DATA
INFILE WF_TRAVELER_MAPPING.data
TRUNCATE
INTO TABLE WF_TRAVELER_MAPPING
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
(
 ENTITY_ID DECIMAL EXTERNAL 
,ENTITY_TYPE DECIMAL EXTERNAL 
,CURRENT_WORKFLOW_ID CHAR(36) 
,CURRENT_TRAVEL_STOP CHAR(36) 
,WF_TRAVELER_MAP_ID SEQUENCE(MAX,1)
)