options  ( skip=1 ) 
LOAD DATA
INFILE WFDEFINITIONRULE.data
TRUNCATE
INTO TABLE WFDEFINITIONRULE
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID CHAR(36)
,ENTITYFLAGS DECIMAL EXTERNAL 
,WORKFLOWID CHAR(36)
,RULETYPE DECIMAL EXTERNAL 
,ACTIONITEM CHAR(36)
,ROLE CHAR(36)
,VERSION DECIMAL EXTERNAL 
)