options  ( skip=1 ) 
LOAD DATA
INFILE WFDEFINITION.data
TRUNCATE
INTO TABLE WFDEFINITION
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID CHAR(36)
,NAME CHAR(200)
,ACTIVATED DECIMAL EXTERNAL  "decode(:ACTIVATED ,'true',1,'false',0, 0)"
,ACTIVATEDDATE DATE "YYYY-MM-DD HH24:MI:SS" 
,ACTIVATEDBY CHAR(36)
,CURRENTVERSION DECIMAL EXTERNAL 
)