options  ( skip=1 ) 
LOAD DATA
INFILE WFENTITYSETTING.data
TRUNCATE
INTO TABLE WFENTITYSETTING
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ENTITYTYPE DECIMAL EXTERNAL 
,DEFAULTWORKFLOWID CHAR(36)
)