options  ( skip=1 ) 
LOAD DATA
INFILE WFSTEPDEFINITIONVERSIONMAP.data
TRUNCATE
INTO TABLE WFSTEPDEFINITIONVERSIONMAP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( VERSION DECIMAL EXTERNAL 
,OLDSTEPDEFINITIONID CHAR(36)
,NEWSTEPDEFINITIONID CHAR(36)
)