options  ( skip=1 ) 
LOAD DATA
INFILE WFSTEPDETAIL.data
TRUNCATE
INTO TABLE WFSTEPDETAIL
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID CHAR(36)
,WFSTEPDEFINITIONID CHAR(36)
,STATUS DECIMAL EXTERNAL 
,ACTIONTYPE DECIMAL EXTERNAL 
,ROLE CHAR(36)
,EMAILTEMPLATE CHAR(200)
,LOCKED DECIMAL EXTERNAL "decode(:LOCKED,'true',1,'false',0, 0)"
,TRIGGERSTYLE DECIMAL EXTERNAL 
,ACTIONITEM CHAR(36)
)