options  ( skip=1 ) 
LOAD DATA
INFILE WFSTEPDEFINITION.data
TRUNCATE
INTO TABLE WFSTEPDEFINITION
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID CHAR(36)
,NAME CHAR(200)
,VERSION DECIMAL EXTERNAL 
,LOCKABLE DECIMAL EXTERNAL "decode(:LOCKABLE,'true',1,'false',0, 0)"
,WORKFLOWID CHAR(36)
)