options  ( skip=1 ) 
LOAD DATA
INFILE WFTRAVELSTOPTASK.data
TRUNCATE
INTO TABLE WFTRAVELSTOPTASK
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID CHAR(36)
,WFTRAVELSTOPID CHAR(36)
,ROLE CHAR(36)
,WFSTEPDEFINITIONDETAILID CHAR(36)
,STATUS DECIMAL EXTERNAL 
,LOCKED DECIMAL EXTERNAL "decode(:LOCKED,'true',1,'false',0, 0)"
,LOCKTYPE DECIMAL EXTERNAL 
,ACTIONTYPE DECIMAL EXTERNAL 
,ACTIONITEM CHAR(36)
,TRIGGERSTYLE DECIMAL EXTERNAL 
)