options  ( skip=1 ) 
LOAD DATA
INFILE WFTRAVELER.data
TRUNCATE
INTO TABLE WFTRAVELER
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ENTITYID DECIMAL EXTERNAL 
,ENTITYTYPE DECIMAL EXTERNAL 
,CURRENTWORKFLOWID CHAR(36)
,CURRENTTRAVELSTOP CHAR(36)
)