options  ( skip=1 ) 
LOAD DATA
INFILE WFTRAVELSTOP.data
TRUNCATE
INTO TABLE WFTRAVELSTOP
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ID CHAR(36)
,WFSTEPDEFINITIONID CHAR(36)
,ARRIVALSTATUS DECIMAL EXTERNAL 
,DEPARTURESTATUS DECIMAL EXTERNAL 
,CAMEFROM CHAR(36)
,NEXTSTOP CHAR(36)
,WFTRAVELERENTITYID DECIMAL EXTERNAL 
,WFTRAVELERENTITYTYPE DECIMAL EXTERNAL 
,ARRIVALTIME DATE "YYYY-MM-DD HH24:MI:SS" 
)