options  ( skip=1 ) 
LOAD DATA
INFILE WORKFLOW.data
TRUNCATE
INTO TABLE WORKFLOW
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( WORKFLOWID DECIMAL EXTERNAL 
,PROCESSSTEPTYPEID DECIMAL EXTERNAL 
,CURRENTSTATUS DECIMAL EXTERNAL 
,ROLE CHAR(36)
,ENTITYTYPEID DECIMAL EXTERNAL 
,ENTITYID DECIMAL EXTERNAL 
,SEQUENCE DECIMAL EXTERNAL 
,DOCUMENTKEY CHAR(36)
,LASTUPDATEDBY CHAR(36)
)