options  ( skip=1 ) 
LOAD DATA
INFILE WORKFLOWNOTIFICATION.data
TRUNCATE
INTO TABLE WORKFLOWNOTIFICATION
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( WORKFLOWNOTIFICATIONID DECIMAL EXTERNAL 
,WORKFLOWID DECIMAL EXTERNAL 
,EMAILADDRESS CHAR(256)
,FIRSTNAME CHAR(100)
,LASTNAME CHAR(100)
,TITLE CHAR(100)
)