options  ( skip=1 ) 
LOAD DATA
INFILE WORKFLOWENDPOINT.data
TRUNCATE
INTO TABLE WORKFLOWENDPOINT
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( ENTITYTYPEID DECIMAL EXTERNAL 
,PROCESSSTEPTYPEID DECIMAL EXTERNAL 
,CURRENTSTATUS DECIMAL EXTERNAL 
)