options  ( skip=1 ) 
LOAD DATA
INFILE WSISTATUS.data
TRUNCATE
INTO TABLE WSISTATUS
FIELDS TERMINATED BY "~"   optionally enclosed by "'" 
 TRAILING NULLCOLS
( WSISTATUSID DECIMAL EXTERNAL 
,STATUSTEXTID CHAR(36)
,STATUSDEFINITIONTEXTID CHAR(36)
,ACTIVE "decode(:ACTIVE ,'true','T','false','F', 'F')"
)